Big update, mainly for gradle and the vuild compoments.

diff --git a/vagrantDevBox/Vagrantfile b/vagrantDevBox/Vagrantfile
--- a/vagrantDevBox/Vagrantfile
+++ b/vagrantDevBox/Vagrantfile
@@ -1,6 +1,7 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 
+require 'fileutils'
 require_relative 'localConfig.rb'
 include LOCAL_CONFIG
 hostDevDir = HOST_DEV_DIR
@@ -11,10 +12,19 @@ javaVersion = "8u241"
 #javaVersionId = "96a7b8442fe848ef90c96a2fad6ed6d1"
 javaRpm = "jdk-#{javaVersion}-linux-x64.rpm"
 
+vagrant_root = File.dirname(__FILE__)
+puts "vagrant_root: #{vagrant_root}"
+
 homeDir = "/home/vagrant"
 localDir = "/usr/local"
 downloadDir = "#{homeDir}/installDownload"
 bashProfileFile = "#{homeDir}/.bashrc"
+
+
+guestStepDir = "#{downloadDir}/steps"
+hostStepDir = "#{hostDevDir}/installDownload/steps"
+FileUtils.mkdir_p hostStepDir
+
 
 # All Vagrant configuration is done below. The "2" in Vagrant.configure
 # configures the configuration version (we support older styles for
@@ -28,7 +38,12 @@ Vagrant.configure(2) do |config|
   # Every Vagrant development environment requires a box. You can search for
   # boxes at https://atlas.hashicorp.com/search.
   #config.vm.box = "bento/centos-7.3"
-  config.vm.box = "centos/7"
+  #config.vm.box = "bento/fedora-latest"
+  config.vm.box = "gameyCamper/FedoraKDE43"
+
+  config.vbguest.auto_update = false
+
+  config.cache.auto_detect = true
 
   # Disable automatic box update checking. If you disable this, then
   # boxes will only be checked for updates when the user runs
@@ -43,10 +58,10 @@ Vagrant.configure(2) do |config|
   # Create a private network, which allows host-only access to the machine
   # using a specific IP.
   config.vm.network "private_network", ip: "192.170.1.6"
-  config.vm.network "forwarded_port", guest: 22, host: 2226
+  #config.vm.network "forwarded_port", guest: 22, host: 2226
 
-  config.ssh.forward_agent=true
-  config.ssh.forward_x11=true
+  #config.ssh.forward_agent=true
+  #config.ssh.forward_x11=true
   
   # Create a public network, which generally matched to bridged network.
   # Bridged networks make the machine appear as another physical device on
@@ -66,26 +81,44 @@ Vagrant.configure(2) do |config|
   #config.vm.synced_folder "#{hostDevDir}/monitorNbn", "#{homeDir}/monitorNbn/monitorNbn", type: "virtualbox", automount: true
   config.vm.synced_folder ".", "/vagrant", disabled: true
 
+  config.vm.disk :disk, size: "30GB", primary: true
+
   # Provider-specific configuration so you can fine-tune various
   # backing providers for Vagrant. These expose provider-specific options.
   # Example for VirtualBox:
   #
   config.vm.provider "virtualbox" do |vb|
     vb.name = "monitorNbnDevBox"
+
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.customize ["modifyvm", :id, "--monitorcount", "#{monitorCount}"]  
 
     # Customize the amount of memory on the VM:
-    vb.memory = "6144"
+    vb.memory = "12288"
     vb.cpus = 4
 	
+    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
     vb.customize ["modifyvm", :id, "--vram", "64"]
     vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
-    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
+	
+#    vb.customize ["storageattach", :id, 
+#                  "--storagectl", "SATA Controller", 
+#                  "--port", "1", "--device", "0", 
+#                  "--type", "dvddrive", 
+#                  "--medium", "emptydrive"]
 	
     #vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/home/vagrant/waterTank", "1"]
   end
+
+  config.trigger.after :destroy do |trigger|
+    trigger.info = "Removing steps..."
+    trigger.ruby do |env|
+      puts "^^^ Destroy Steps"
+      FileUtils.rm_rf(Dir["#{hostStepDir}/*"], verbose: true)
+    end
+  end
+
   #
   # View the documentation for the provider you are using for more
   # information on available options.
@@ -106,59 +139,83 @@ Vagrant.configure(2) do |config|
   # SHELL
   
   config.vm.provision "shell", inline: <<-SHELL
-    sudo yum -y install deltarpm
-    sudo yum -y update
-    sudo yum install zlib.i686 ncurses-libs.i686 bzip2-libs.i686
-    sudo yum install -y augeas
-    sudo yum install xorg-x11-xauth
-    sudo yum -y groupinstall "GNOME Desktop"
-    sudo rpm -e initial-setup initial-setup-gui    
-    sudo systemctl set-default graphical.target
-    sudo systemctl start graphical.target
-    sudo yum -y install xterm
-    sudo yum -y install xclock
-	sudo yum -y install dconf-editor
-	sudo yum -y install git
+    dnf -y update
+
+    dnf install zlib.i686 ncurses-libs.i686 bzip2-libs.i686
+    dnf -y install augeas
+
+
+    echo "--- Install apps and tools"
+	dnf -y install gparted parted cloud-utils-growpart
+    dnf -y install ansible helm
+
+    echo "--- Resise main disk, if required"
+	CURRENT_DISK_SIZE=`df -h | grep -E " /$" | awk '{print $2}'`
+    echo "Current root disk size $CURRENT_DISK_SIZE"
+    if [ "$CURRENT_DISK_SIZE" != "30GB" ]; then
+      growpart /dev/sda 3
+	  xfs_growfs /
+	fi
+
+    timedatectl set-timezone Australia/Sydney
+
   SHELL
 
+
+  unless File.file?("#{hostStepDir}/01-userAutoLogin")
+    config.vm.provision "shell", reboot: true, inline: <<-SHELL
+      echo "Configure user autologin."
+      sed -i.bak1 -e 's/#* *User=.*/User=vagrant/' /etc/sddm.conf
+	  sed -i.bak2 -e 's/#* *Session=.*/Session=plasma.desktop/' /etc/sddm.conf
+	  
+      touch "#{guestStepDir}/01-userAutoLogin"
+    SHELL
+  end
+
+  unless File.file?("#{hostStepDir}/02-desktopSetup")
+    config.vm.provision "shell", privileged: false, inline: <<-SHELL
+
+      if [ ! -f ~/installDownload/backdrop.jpg ]; then
+        echo "ERROR: wallpaper image (backdrop.jpg) cannot be found."
+		exit 1
+      fi
+	  
+	  cp -v --update ~/installDownload/backdrop.jpg ~/Pictures/backdrop.jpg
+      echo "Disable screen lock."
+	  plasma-apply-wallpaperimage ~/Pictures/backdrop.jpg
+	  plasma-apply-colorscheme BreezeLight
+
+      echo "Disable screen lock."
+	  kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false
+	  kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key LockOnResume false
+	  kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Timeout 0
+	  
+	  echo "Git setup."
+	  git config --global user.email "spam.spam.spam@ineson.me"
+	  git config --global user.name "GameyCamper"
+
+      touch "#{guestStepDir}/02-desktopSetup"
+    SHELL
+  end
+
   config.vm.provision "shell", inline: <<-SHELL
-    echo "Configure user and desktop settings."
-	sudo timedatectl set-timezone Australia/Sydney
-    # Set screen lockout to 1 hour
-    sudo -u vagrant dbus-launch gsettings set org.gnome.desktop.session idle-delay 3600
-    # Set font and icon sizes
-	sudo -u vagrant dbus-launch gsettings set org.gnome.desktop.interface text-scaling-factor 0.75
-    sudo -u vagrant dbus-launch gsettings set org.gnome.nautilus.icon-view default-zoom-level small	
-	sudo -u vagrant dbus-launch gsettings set org.gnome.nautilus.icon-view default-zoom-level small
-	#sudo -u vagrant dbus-launch gsettings set org.gnome.desktop.interface toolbar-icons-size small
-	#xset s off
-    #xset s noblank
+	dnf -y install @kde-apps @kde-software-development @admin-tools @system-tools @editors
+
   SHELL
-#[vagrant@localhost ~]$ gsettings set org.gnome.desktop.session idle-delay 0
-#[vagrant@localhost ~]$ gsettings get org.gnome.desktop.screensaver lock-enabled
-#true
 
   
-  
-  config.vm.provision "shell", inline: <<-SHELL
-    echo "Installing KVM"
-    sudo yum -y install qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client virt-install virt-viewer bridge-utils
-	systemctl start libvirtd
-    systemctl enable libvirtd
-  SHELL
+#  config.vm.provision "shell", inline: <<-SHELL
+#    echo "Installing KVM"
+#    yum -y install qemu-kvm qemu-img virt-manager libvirt libvirt-python libvirt-client virt-install virt-viewer bridge-utils
+#	systemctl start libvirtd
+#    systemctl enable libvirtd
+#  SHELL
   
   # Configure autologin as the vagrant user.
-  config.vm.provision "shell", path: "configUser.sh"
-
-  # Is a restart required?
-  
-  config.vm.provision "shell", inline: <<-SHELL
-    echo "Removing OpenJDK"
-    rpm -qa | grep "openjdk" | while read line ; do echo "- removing Java $line"; sudo yum -y erase $line ; done
-  SHELL
+  #config.vm.provision "shell", path: "configUser.sh"
 
   
-  # Install Java - Oracle Version
+  # Install Java8 - Oracle Version
   config.vm.provision "shell", inline: <<-SHELL
     if ! [[ $(rpm -qa | grep 'jdk[0-9]') = jdk* ]]; then
       echo "Installing Oracle Java"
@@ -170,7 +227,8 @@ Vagrant.configure(2) do |config|
 #	      wget -O "#{javaRpm}" -c --content-disposition "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=241523_1f5b5a70bf22433b84d0e960903adac8"
 	  fi
 	  ls -l *.rpm
-      sudo yum localinstall -y "#{javaRpm}"
+	  rpm -ivh --nodigest --nofiledigest "#{javaRpm}"
+#      dnf install -y "#{javaRpm}"
 #      sudo yum localinstall -y "jdk-#{javaVersion}-linux-x64.rpm"
 #      rm jdk-*.rpm*
 	else
@@ -178,56 +236,75 @@ Vagrant.configure(2) do |config|
     fi
   SHELL
 
-  epelRpm = "epel-release-latest-7.noarch.rpm"
-
   config.vm.provision "shell", inline: <<-SHELL
-    echo "Add epel"
-    cd "#{downloadDir}"
-	ls -l
-    if [ ! -f "#{epelRpm}" ]; then
-      wget --quiet http://dl.fedoraproject.org/pub/epel/#{epelRpm}
-    fi
-      sudo rpm -ivh #{epelRpm}
-    ls -l *.rpm
-	sudo yum repolist
+    dnf -y remove java-25-openjdk-headless.x86_64
+    echo "Latest OpenJDK compiler"
+	dnf -y install java-latest-openjdk-devel.x86_64 java-latest-openjdk-javadoc.x86_64 java-latest-openjdk-src.x86_64
+
+    echo "Set OpenJDK alternatives to the lastest."
+	sudo alternatives --set java /usr/lib/jvm/java-latest-openjdk/bin/java
+	sudo alternatives --set javac /usr/lib/jvm/java-latest-openjdk/bin/javac
+
   SHELL
+
+#  epelRpm = "epel-release-latest-7.noarch.rpm"
+#
+#  config.vm.provision "shell", inline: <<-SHELL
+#    echo "Add epel"
+#    cd "#{downloadDir}"
+#	ls -l
+#    if [ ! -f "#{epelRpm}" ]; then
+#      wget --quiet http://dl.fedoraproject.org/pub/epel/#{epelRpm}
+#    fi
+#      sudo rpm -ivh #{epelRpm}
+#    ls -l *.rpm
+#	yum repolist
+#  SHELL
   
   # Install sdkman which is required for groovy and gradle.
-  config.vm.provision "shell", inline: <<-SHELL
-    if [ ! -d /usr/local/sdkman ]; then
-      export SDKMAN_DIR="/usr/local/sdkman" && curl -s get.sdkman.io | bash
+  config.vm.provision "shell", privileged: false, inline: <<-SHELL
+    if [ ! -d $HOME/.sdkman ]; then
+      curl -s "https://get.sdkman.io" | bash
+	  source "$HOME/.sdkman/bin/sdkman-init.sh"
+      sdk version
 	fi
   SHELL
 
   # Install groovy, gradle and maven.
-  config.vm.provision "shell", inline: <<-SHELL
-	export SDKMAN_DIR="/usr/local/sdkman"
-    source "/usr/local/sdkman/bin/sdkman-init.sh"
-    echo "sdkman_auto_answer=true" >> /usr/local/sdkman/etc/config
-    if [ ! -f /etc/profile.d/groovy.sh ]; then
+  config.vm.provision "shell", privileged: false, inline: <<-SHELL
+    echo "Install tools"
+    source "$HOME/.sdkman/bin/sdkman-init.sh"
+	sdk version
+ #   echo "sdkman_auto_answer=true" >> $HOME/.sdkman/etc/config
+ #   if [ ! -f ~/.sdkman/candidates/groovy/current/bin/groovy ]; then
       echo "Install Groovy"
 	  sdk install groovy > /dev/null
-      echo "export GROOVY_HOME=/usr/local/sdkman/candidates/groovy/current" > /etc/profile.d/groovy.sh
-      echo "export PATH=\\$PATH:\\$GROOVY_HOME/bin" >> /etc/profile.d/groovy.sh
-      chmod +rx /etc/profile.d/groovy.sh
-	fi
-    groovy -v
+#      echo "export GROOVY_HOME=$HOME/.sdkman/candidates/groovy/current" > /etc/profile.d/groovy.sh
+#      echo "export PATH=\\$PATH:\\$GROOVY_HOME/bin" >> /etc/profile.d/groovy.sh
+#      chmod +rx /etc/profile.d/groovy.sh
+#	fi
+      echo "Installed Groovy"
 
-    if [ ! -f /etc/profile.d/gradle.sh ]; then
+    if [ ! -f ~/.sdkman/candidates/gradle/current/bin/gradle ]; then
       echo "Install Gradle"
       sdk install gradle > /dev/null
-      echo "export GRADLE_HOME=/usr/local/sdkman/candidates/gradle/current" > /etc/profile.d/gradle.sh
-      echo "export PATH=\\$PATH:\\$GRADLE_HOME/bin" >> /etc/profile.d/gradle.sh
-      chmod +rx /etc/profile.d/gradle.sh
+#      echo "export GRADLE_HOME=/usr/local/sdkman/candidates/gradle/current" > /etc/profile.d/gradle.sh
+#      echo "export PATH=\\$PATH:\\$GRADLE_HOME/bin" >> /etc/profile.d/gradle.sh
+#      chmod +rx /etc/profile.d/gradle.sh
 	fi
+
+    echo "Installed Gradle"
+
+    source "$HOME/.sdkman/bin/sdkman-init.sh"
+    groovy -v
     gradle -v
   SHELL
 
 desktopFilename = "#{homeDir}/Desktop/Spring Tool Suite.desktop"
 #desktopFilename = "#{homeDir}/.local/share/applications/Spring Tool Suite.desktop"
 
-stsVersion = "sts-4.5.1.RELEASE"
-stsTar = "spring-tool-suite-4-4.5.1.RELEASE-e4.14.0-linux.gtk.x86_64.tar.gz"
+stsVersion = "sts-4.32.2.RELEASE"
+stsTar = "spring-tools-for-eclipse-4.32.2.RELEASE-e4.37.0-linux.gtk.x86_64.tar.gz"
 
 
   config.vm.provision "shell", inline: <<-SHELL
@@ -239,11 +316,12 @@ stsTar = "spring-tool-suite-4-4.5.1.RELEASE-e4.14.0-linux.gtk.x86_64.tar.gz"
       echo "Download Spring STS"
       cd "#{homeDir}/Apps/eclipse"
 	  ls -l
-      if [ ! -f "#{stsTar}" ]; then
-        wget --quiet --no-cookies --no-check-certificate "https://download.springsource.com/release/STS4/4.5.1.RELEASE/dist/e4.14/spring-tool-suite-4-4.5.1.RELEASE-e4.14.0-linux.gtk.x86_64.tar.gz"
+	  ls -l "#{downloadDir}"
+      if [ ! -f "#{downloadDir}/#{stsTar}" ]; then
+        wget --quiet --no-cookies --no-check-certificate "https://cdn.spring.io/spring-tools/release/STS4/4.32.2.RELEASE/dist/e4.37/spring-tools-for-eclipse-4.32.2.RELEASE-e4.37.0-linux.gtk.x86_64.tar.gz" -o #(downloadDir)/#{stsTar}
 	  fi
       ls -l *.gz
-      tar -xvf #{stsTar}
+      tar -xvf #{downloadDir}/#{stsTar}
 
 	  chown -R vagrant:vagrant "#{homeDir}/Apps/eclipse"
 	fi
